#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app-peach-web" --action="stop"
ynh_systemctl --service="$app-tilde-sbot" --action="stop"

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

# this will most likely adjust NGINX config correctly
ynh_config_change_url_nginx

#=================================================
# SPECIFIC MODIFICATIONS
#=================================================

# change domain in config files for peach-web and tilde-sbot
ynh_replace --match=$old_domain --replace=$new_domain --file=$install_dir/config/config.yml
ynh_replace --match=$old_domain --replace=$new_domain --file=$install_dir/.ssb-tilde/tilde-sbot.toml

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service="$app-tilde-sbot" --action="start"
ynh_systemctl --service="$app-peach-web" --action="start"

# for some reason a restart of peach-web is needed
ynh_systemctl --service="$app-peach-web" --action="restart"
ynh_systemctl --service="$app-tilde-sbot" --action="restart"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
