#!/bin/bash

## this script is only run if actual change to domain/path is detected, if you're here either $domain or $path changed
## new location is available via $domain and $path (or $new_domain and $new_path variables if you want to be explicit)
## old values are available via, you guessed it, $old_domain and $old_path

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app-peach-web" --action="stop"
ynh_systemctl --service="$app-tilde-sbot" --action="stop"

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

# this will most likely adjust NGINX config correctly
ynh_config_change_url_nginx

#=================================================
# SPECIFIC MODIFICATIONS
#=================================================

# change domain in config files for peach-web and tilde-sbot
ynh_replace --match=$old_domain --replace=$new_domain --file=$install_dir/config/config.yml
ynh_replace --match=$old_domain --replace=$new_domain --file=$install_dir/.ssb-tilde/tilde-sbot.toml

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service="$app-tilde-sbot" --action="start"
ynh_systemctl --service="$app-peach-web" --action="start"

# for some reason a restart of peach-web is needed
ynh_systemctl --service="$app-peach-web" --action="restart"
ynh_systemctl --service="$app-tilde-sbot" --action="restart"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
