#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

peach_web_service=$app-peach-web
tilde_sbot_service=$app-tilde-sbot
tilde_dir=$install_dir/.ssb-tilde

ynh_app_setting_set --key=peach_web_service --value=$peach_web_service
ynh_app_setting_set --key=tilde_sbot_service --value=$tilde_sbot_service
ynh_app_setting_set --key=tilde_dir --value=$tilde_dir

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir"
chown -R "$app:$app" "$install_dir"


#=================================================
# APP INITIAL CONFIGURATION
#=================================================

mkdir -p $install_dir/config
mkdir -p $install_dir/.ssb-tilde

ynh_script_progression "Adding a configuration file for tilde-sbot" 
ynh_config_add --template="tilde-sbot.toml" --destination="$tilde_dir/tilde-sbot.toml"
chmod 600 "$tilde_dir/tilde-sbot.toml"
chown -R $app:$app "$tilde_dir/"

ynh_script_progression "Adding a configuration file for peach-web" 
ynh_config_add --template="peach.yml" --destination="$install_dir/config/config.yml"
chmod 600 "$install_dir/config/config.yml"
chown $app:$app "$install_dir/config/config.yml"

ynh_script_progression "Creating /etc/sudoers.d/$app" 
mkdir -p /etc/sudoers.d/
ynh_config_add --template="sudoers" --destination="/etc/sudoers.d/$app"
chown root:root /etc/sudoers.d/$app
chmod 440 /etc/sudoers.d/$app

chown -R $app:$app $install_dir
chmod -R u+rwX,g+rwX $install_dir

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add_systemd --service=$app-peach-web --template=peach-web.service
ynh_config_add_systemd --service=$app-tilde-sbot --template=tilde-sbot.service

# add services to ynh
yunohost service add "$app-peach-web" --description="peach-web service" --log="/var/log/$app/$app-peach-web.log"
yunohost service add "$app-tilde-sbot" --needs_exposed_ports="$port_ssb" --description="tilde-sbot service" --log="/var/log/$app/$app-tilde-sbot.log"

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate

# TODO: figure out fail2ban
# Create a dedicated Fail2Ban config
# ynh_config_add_fail2ban --logpath="/var/log/nginx/${domain}-error.log" --failregex="Regex to match into the log for a failed login"


#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd services..."

# Start a systemd service
ynh_systemctl --service="$app-tilde-sbot" --action="start"
ynh_systemctl --service="$app-peach-web" --action="start"

# for some reason a restart of peach-web is needed
ynh_systemctl --service="$app-peach-web" --action="restart"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
