#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers


#=================================================
# REMOVE SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

### This should be a symetric version of what happens in the install script

ynh_config_remove_fail2ban

ynh_config_remove_logrotate

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status "$app-peach-web" >/dev/null; then
    yunohost service remove "$app-peach-web"
fi
if ynh_hide_warnings yunohost service status "$app-tilde-sbot" >/dev/null; then
    yunohost service remove "$app-tilde-sbot"
fi

ynh_config_remove_systemd --service=$app-peach-web
ynh_config_remove_systemd --service=$app-tilde-sbot

ynh_config_remove_nginx


#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
