#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app-peach-web" --action="stop"
ynh_systemctl --service="$app-tilde-sbot" --action="stop"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir" --full_replace --keep="config .ssb-tilde"

#=================================================
# REAPPLY SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Readding system configurations related to $app..."

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add_systemd --service=$app-peach-web --template=peach-web.service
ynh_config_add_systemd --service=$app-tilde-sbot --template=tilde-sbot.service

yunohost service add "$app-peach-web" --description="peach-web service" --log="/var/log/$app/$app-peach-web.log"
yunohost service add "$app-tilde-sbot" --needs_exposed_ports="$port_ssb" --description="tilde-sbot service" --log="/var/log/$app/$app-tilde-sbot.log"

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate /var/log/$app/$app-peach-web.log
ynh_config_add_logrotate /var/log/$app/$app-tilde-sbot.log

# Create a dedicated Fail2Ban config
ynh_config_add_fail2ban --logpath="/var/log/$app/$app-peach-web.log" --failregex='^.*peach_web::routes::authentication::login\] Unsuccessful login attempt from "<HOST>"$'

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service="$app-tilde-sbot" --action="start"
ynh_systemctl --service="$app-peach-web" --action="start"

# for some reason a restart of peach-web is needed
ynh_systemctl --service="$app-peach-web" --action="restart"
ynh_systemctl --service="$app-tilde-sbot" --action="restart"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
