#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app-peach-web" --action="stop"
ynh_systemctl --service="$app-tilde-sbot" --action="stop"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

### ynh_setup_source can wipe the destination dir if called with --full_replace.
### On upgrade, that is certainly what you want, to remove any old source file that
### does not exist in the new version of the software.
### You can list with --keep every file/directory to *not* wipe or overwrite,
### useful for configuration files, data directories, or plugins.
# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir" --full_replace --keep="config .ssb-tilde"

chown -R "$app:$app" "$install_dir"
chmod -R u+rwX,g+rwX $install_dir


#=================================================
# REAPPLY SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Readding system configurations related to $app..."

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add_systemd --service=$app-peach-web --template=peach-web.service
ynh_config_add_systemd --service=$app-tilde-sbot --template=tilde-sbot.service

### TODO: check this port thing again
### --needs_exposed_ports "$port" a list of ports that needs to be publicly exposed
###                               which will then be checked by YunoHost's diagnosis system
###                               (N.B. DO NOT USE THIS if the port is only internal!!!)
yunohost service add "$app-peach-web" --description="peach-web service" --log="/var/log/$app/$app-peach-web.log"
yunohost service add "$app-tilde-sbot" --needs_exposed_ports="$port_ssb" --description="tilde-sbot service" --log="/var/log/$app/$app-tilde-sbot.log"

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate

# TODO: figure out fail2ban
# Create a dedicated Fail2Ban config
# ynh_config_add_fail2ban --logpath="/var/log/nginx/${domain}-error.log" --failregex="Regex to match into the log for a failed login"


#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service="$app-tilde-sbot" --action="start"
ynh_systemctl --service="$app-peach-web" --action="start"

# for some reason a restart of peach-web is needed
ynh_systemctl --service="$app-peach-web" --action="restart"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
